In [6]:
import pandas as pd
import numpy as np

In [3]:
# Create Employee Dataset
data = {
    'employee_id': [101, 102, 103, 104, 105],
    'employee_name': ['Akhil', 'Meghana', 'Rohit', 'Pooja', 'Harish'],
    'department': ['IT', 'HR', 'Finance', 'Marketing', 'IT'],
    'salary': [50000, 45000, 60000, 55000, 70000],
    'bonus': [5000, 4000, 6000, 5500, 7000],
    'joining_date': [
        '2021-01-15',
        '2020-06-20',
        '2019-03-10',
        '2022-08-05',
        '2018-11-01'
    ]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
# Display Dataset
print("Original Dataset")
print(df)

Original Dataset
   employee_id employee_name department  salary  bonus joining_date
0          101         Akhil         IT   50000   5000   2021-01-15
1          102       Meghana         HR   45000   4000   2020-06-20
2          103         Rohit    Finance   60000   6000   2019-03-10
3          104         Pooja  Marketing   55000   5500   2022-08-05
4          105        Harish         IT   70000   7000   2018-11-01

In [7]:
# Calculate Total Salary
df['total_salary'] = df['salary'] + df['bonus']

df

,employee_id,employee_name,department,salary,bonus,joining_date,total_salary
0,101,Akhil,IT,50000,5000,2021-01-15,55000
1,102,Meghana,HR,45000,4000,2020-06-20,49000
2,103,Rohit,Finance,60000,6000,2019-03-10,66000
3,104,Pooja,Marketing,55000,5500,2022-08-05,60500
4,105,Harish,IT,70000,7000,2018-11-01,77000

In [10]:
# Convert joining_date to datetime
df['joining_date'] = pd.to_datetime(df['joining_date'])

df

,employee_id,employee_name,department,salary,bonus,joining_date,total_salary
0,101,Akhil,IT,50000,5000,2021-01-15,55000
1,102,Meghana,HR,45000,4000,2020-06-20,49000
2,103,Rohit,Finance,60000,6000,2019-03-10,66000
3,104,Pooja,Marketing,55000,5500,2022-08-05,60500
4,105,Harish,IT,70000,7000,2018-11-01,77000

In [11]:
# Extract Year
df['joining_year'] = df['joining_date'].dt.year

df

,employee_id,employee_name,department,salary,bonus,joining_date,total_salary,joining_year
0,101,Akhil,IT,50000,5000,2021-01-15,55000,2021
1,102,Meghana,HR,45000,4000,2020-06-20,49000,2020
2,103,Rohit,Finance,60000,6000,2019-03-10,66000,2019
3,104,Pooja,Marketing,55000,5500,2022-08-05,60500,2022
4,105,Harish,IT,70000,7000,2018-11-01,77000,2018

In [12]:
# Create Salary Category
df['salary_category'] = np.where(
    df['salary'] >= 55000,
    'High',
    'Medium'
)

df

,employee_id,employee_name,department,salary,bonus,joining_date,total_salary,joining_year,salary_category
0,101,Akhil,IT,50000,5000,2021-01-15,55000,2021,Medium
1,102,Meghana,HR,45000,4000,2020-06-20,49000,2020,Medium
2,103,Rohit,Finance,60000,6000,2019-03-10,66000,2019,High
3,104,Pooja,Marketing,55000,5500,2022-08-05,60500,2022,High
4,105,Harish,IT,70000,7000,2018-11-01,77000,2018,High

In [13]:
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    (df['salary'] < (Q1 - 1.5 * IQR)) |
    (df['salary'] > (Q3 + 1.5 * IQR))
]

print("Outliers:")
print(outliers)

Outliers:
Empty DataFrame
Columns: [employee_id, employee_name, department, salary, bonus, joining_date, total_salary, joining_year, salary_category]
Index: []

In [14]:
print("Transformed Dataset")
print(df)

Transformed Dataset
   employee_id employee_name department  salary  bonus joining_date  \
0          101         Akhil         IT   50000   5000   2021-01-15
1          102       Meghana         HR   45000   4000   2020-06-20
2          103         Rohit    Finance   60000   6000   2019-03-10
3          104         Pooja  Marketing   55000   5500   2022-08-05
4          105        Harish         IT   70000   7000   2018-11-01

   total_salary  joining_year salary_category
0         55000          2021          Medium
1         49000          2020          Medium
2         66000          2019            High
3         60500          2022            High
4         77000          2018            High